services:
    _defaults:
        autowire: true
    DigipolisGent\Domainator9k\AppTypes\DrupalEightBundle\CacheClearer\DrupalEightCacheClearer:
        tags:
            - {name: domainator.cacheclearer, for: DigipolisGent\Domainator9k\AppTypes\DrupalEightBundle\Entity\DrupalEightApplication}
